import { Link } from "react-router-dom";
import { useEffect } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Terms = () => {
  useEffect(() => {
    document.title = "Else | Terms and conditions";
  }, []);

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      <main className="flex-1 px-5 pb-16 pt-8 sm:px-8 md:px-16 lg:px-24 2xl:px-32">
        <Link
          to="/"
          className="inline-flex items-center gap-1 text-sm text-foreground hover:opacity-70 transition-opacity mb-12"
        >
          ← Back to home
        </Link>

        <div className="flex flex-col gap-8 md:flex-row md:gap-16 lg:gap-24">
          <div className="md:w-1/3 md:sticky md:top-8 md:self-start">
            <h1 className="text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
              Terms and conditions
            </h1>
            <p className="mt-4 text-sm text-muted-foreground">
              Last updated: March 21st, 2026
            </p>
          </div>

          <div className="md:w-2/3 space-y-10 text-foreground/90 text-[15px] leading-relaxed text-justify">
            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">1. Introduction and acceptance of terms</h2>
              <p className="mb-4">
                Welcome to Else. These Terms and Conditions ("Terms") govern your access to and use of Else\u2019s AI-powered career assistant service, including our website at https://tryelse.xyz, any associated applications, and all related services (collectively, the "Service").
              </p>
              <p className="mb-4">
                By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not access or use the Service.
              </p>
              <p className="mb-4">
                Else ("we," "us," or "our") is a European company that provides AI-driven career support, helping professionals find and navigate their next career opportunities.
              </p>
              <p className="font-medium">
                IMPORTANT: These Terms apply to all users of the Service, regardless of their location. By using the Service, you expressly agree that any dispute arising from or relating to these Terms or the Service will be governed exclusively by European legislation and resolved exclusively in European courts.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">2. Definitions</h2>
              <p className="mb-3">For purposes of these Terms:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>"User," "you," or "your" refers to any individual or entity accessing or using the Service.</li>
                <li>"Account" refers to the unique account created for you to access the Service.</li>
                <li>"Content" means any data, text, information, queries, responses, or other materials submitted to, generated by, or accessible through the Service.</li>
                <li>"User Content" refers to Content that you submit or provide to the Service.</li>
                <li>"AI Agent" refers to the artificial intelligence system that powers our career assistance features.</li>
                <li>"Subscription" refers to your paid subscription plan that grants you access to the Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">3. Eligibility</h2>
              <p className="mb-4">You must be at least 16 years old to use the Service. By using the Service, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms.</p>
              <p>If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">4. Account registration and security</h2>
              <p className="mb-3 font-medium">4.1 Account creation</p>
              <p className="mb-3">To access the Service, you must create an account. You agree to:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Provide accurate, current, and complete information during registration.</li>
                <li>Maintain and promptly update your account information.</li>
                <li>Maintain the security of your password and account credentials.</li>
                <li>Accept all responsibility for activities that occur under your account.</li>
                <li>Notify us immediately of any unauthorized access or security breach.</li>
              </ul>
              <p className="mb-3 mt-6 font-medium">4.2 Account security</p>
              <p>You are responsible for maintaining the confidentiality of your account login credentials. You agree not to share your account with others or allow others to access your account. We are not liable for any loss or damage arising from your failure to protect your account credentials.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">5. Service description</h2>
              <p className="mb-3">Else provides an AI-powered assistant designed to support professionals by:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Answering career-related questions and providing guidance.</li>
                <li>Assisting with job search and career decisions based on industry best practices.</li>
                <li>Facilitating comparisons between different career opportunities or paths.</li>
                <li>Providing insights derived from career frameworks and methodologies.</li>
              </ul>
              <p className="mt-3">The Service is provided "as is" and we reserve the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">6. Use of the service</h2>
              <p className="mb-3 font-medium">6.1 License grant</p>
              <p className="mb-4">Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your personal and professional purposes.</p>
              <p className="mb-3 font-medium">6.2 Restrictions</p>
              <p className="mb-3">You agree not to:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Use the Service for any illegal purpose or in violation of any applicable laws.</li>
                <li>Attempt to gain unauthorized access to the Service or related systems.</li>
                <li>Interfere with or disrupt the integrity or performance of the Service.</li>
                <li>Reverse engineer, decompile, or disassemble any aspect of the Service.</li>
                <li>Use automated systems (bots, scrapers) to access the Service without authorization.</li>
                <li>Remove, alter, or obscure any proprietary notices on the Service.</li>
                <li>Use the Service to develop competing products or services.</li>
                <li>Submit false, misleading, or malicious information.</li>
                <li>Violate the intellectual property rights of Else or any third party.</li>
                <li>Attempt to train competing AI models using outputs from our Service.</li>
                <li>Share your account credentials or allow unauthorized access to your account.</li>
                <li>Resell, sublicense, or redistribute access to the Service without authorization.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">7. User content and data</h2>
              <p className="mb-3 font-medium">7.1 Your content</p>
              <p className="mb-4">You retain ownership of all User Content you submit to the Service. By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, store, process, and transmit your User Content solely to provide and improve the Service.</p>
              <p className="mb-3 font-medium">7.2 Responsibility for user content</p>
              <p className="mb-3">You are solely responsible for your User Content. You represent and warrant that:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>You own or have the necessary rights to your User Content.</li>
                <li>Your User Content does not violate any applicable laws or third-party rights.</li>
                <li>Your User Content does not contain viruses, malware, or harmful code.</li>
              </ul>
              <p className="mb-3 mt-6 font-medium">7.3 Data processing</p>
              <p>We process your User Content in accordance with our Privacy Policy. Your queries and inputs are processed by our AI Agent to provide personalized responses and recommendations.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">8. AI-generated content and disclaimers</h2>
              <p className="mb-3 font-medium">8.1 Nature of AI responses</p>
              <p className="mb-4">The Service uses artificial intelligence to generate responses and recommendations. While we strive for accuracy, AI-generated content may not always be accurate, complete, or appropriate for your specific situation.</p>
              <p className="mb-3 font-medium">8.2 No professional advice</p>
              <p className="mb-4">The Service provides general information and guidance only. It does not constitute professional advice (legal, financial, strategic, or otherwise). You should not rely solely on AI-generated responses for critical career decisions.</p>
              <p className="mb-3 font-medium">8.3 Your independent judgment</p>
              <p>You acknowledge that you are responsible for independently evaluating all AI-generated content and making your own decisions. We are not responsible for any decisions you make based on information provided by the Service.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">9. Intellectual property rights</h2>
              <p className="mb-3 font-medium">9.1 Else\u2019s intellectual property</p>
              <p className="mb-4">The Service, including its software, algorithms, user interface, design, branding, and all related intellectual property, is owned by Else or our licensors. These Terms do not grant you any rights to our trademarks, logos, or other brand features.</p>
              <p className="mb-3 font-medium">9.2 Feedback</p>
              <p>If you provide us with any feedback, suggestions, or ideas about the Service, you grant us the right to use such feedback without any obligation to you.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">10. Subscription and payment terms</h2>
              <p className="mb-3 font-medium">10.1 Payment</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>You agree to pay all applicable fees as described at the time of purchase.</li>
                <li>Fees are charged in advance on a recurring basis (monthly or annually, as selected).</li>
                <li>Payment is processed by third-party payment processors.</li>
                <li>You authorize us to charge your payment method for all applicable fees.</li>
                <li>You are responsible for all taxes associated with your subscription.</li>
              </ul>
              <p className="mb-3 mt-6 font-medium">10.2 Automatic renewal</p>
              <p className="mb-4">Your subscription will automatically renew at the end of each billing period unless you cancel before the renewal date. Cancellation will be effective at the end of your current billing period.</p>
              <p className="mb-3 font-medium">10.3 Price changes</p>
              <p className="mb-4">We may change our subscription prices at any time. Price changes will be effective at the start of your next billing period after we provide you with at least 30 days\u2019 advance notice via email.</p>
              <p className="mb-3 font-medium">10.4 Payment failures</p>
              <p>If a payment fails, we will attempt to charge your payment method again. If payment fails repeatedly, we reserve the right to suspend or terminate your access to the Service.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">11. Termination and suspension</h2>
              <p className="mb-3 font-medium">11.1 Termination by you</p>
              <p className="mb-4">You may cancel your subscription at any time through your account settings or by contacting us at info@tryelse.xyz. You will continue to have access to the Service until the end of your paid period.</p>
              <p className="mb-3 font-medium">11.2 Termination by us</p>
              <p className="mb-3">We may suspend or terminate your access to the Service at any time, including if:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>You violate these Terms.</li>
                <li>Your use of the Service poses a security risk or violates applicable laws.</li>
                <li>Your payment fails or your account becomes delinquent.</li>
                <li>We cease offering the Service.</li>
              </ul>
              <p className="mb-3 mt-6 font-medium">11.3 Effect of termination</p>
              <p className="mb-3">Upon termination:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Your right to use the Service will immediately cease.</li>
                <li>We may delete your account and User Content in accordance with our data retention policy.</li>
                <li>You will have 30 days to export your User Content before it is permanently deleted.</li>
                <li>Provisions that by their nature should survive termination will remain in effect.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">12. Warranties and disclaimers</h2>
              <p className="mb-4 font-medium">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
              <p className="mb-4">THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p>
              <p className="mb-3">WE DO NOT WARRANT THAT:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>The Service will be uninterrupted, secure, or error-free.</li>
                <li>The results obtained from the Service will be accurate, reliable, or complete.</li>
                <li>Any errors or defects in the Service will be corrected.</li>
                <li>The Service will meet your requirements or expectations.</li>
              </ul>
              <p className="mt-4">YOU ACKNOWLEDGE THAT AI-GENERATED CONTENT MAY CONTAIN ERRORS, INACCURACIES, OR INAPPROPRIATE SUGGESTIONS. YOU USE THE SERVICE AT YOUR OWN RISK.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">13. Limitation of liability</h2>
              <p className="mb-4">IN NO EVENT SHALL ELSE, ITS AFFILIATES, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</p>
              <p className="mb-4">OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR \u20ac100, WHICHEVER IS GREATER.</p>
              <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IN SUCH JURISDICTIONS, OUR LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">14. Indemnification</h2>
              <p className="mb-3">You agree to indemnify, defend, and hold harmless Else, its affiliates, and their respective directors, officers, employees, and agents from and against any claims arising out of or related to:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Your use of the Service.</li>
                <li>Your User Content.</li>
                <li>Your violation of these Terms.</li>
                <li>Your violation of any rights of another party.</li>
                <li>Your violation of applicable laws or regulations.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">15. Data processing and compliance</h2>
              <p className="mb-3 font-medium">15.1 Data controller and processor</p>
              <p className="mb-4">When you use the Service, Else acts as the data controller for your personal information. For User Content you submit that contains personal data of third parties, you act as the data controller and Else acts as a data processor.</p>
              <p className="mb-3 font-medium">15.2 Sub-processors</p>
              <p className="mb-4">You acknowledge and agree that we may engage third-party sub-processors, including AI service providers, to process data on our behalf.</p>
              <p className="mb-3 font-medium">15.3 Cross-border data transfers</p>
              <p>You acknowledge that your data may be transferred to and processed in countries other than your own. We implement appropriate safeguards for such transfers as described in our Privacy Policy.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">16. Confidentiality</h2>
              <p className="mb-3">We understand that your User Content may contain confidential information. We will:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Treat your User Content as confidential.</li>
                <li>Not disclose your User Content to third parties except as necessary to provide the Service or as required by law.</li>
                <li>Implement reasonable security measures to protect your User Content.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">17. Third-party services and links</h2>
              <p>The Service may contain links to third-party websites, services, or resources. We do not endorse and are not responsible for the content, products, or services provided by third parties.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">18. Modifications to terms</h2>
              <p className="mb-3">We may modify these Terms at any time. We will notify you of material changes by:</p>
              <ul className="space-y-2 list-disc pl-5">
                <li>Posting the updated Terms on our website.</li>
                <li>Updating the "Last updated" date.</li>
                <li>Sending you an email notification at least 30 days before significant changes take effect.</li>
              </ul>
              <p className="mt-3">Your continued use of the Service after such modifications constitutes your acceptance of the updated Terms.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">19. Dispute resolution and governing law</h2>
              <p className="mb-3 font-medium">19.1 Governing law</p>
              <p className="mb-4">These Terms shall be governed by and construed in accordance with the laws of the European Union and the applicable laws of the country where Else is established.</p>
              <p className="mb-3 font-medium">19.2 Dispute resolution</p>
              <p className="mb-4">The parties agree to first attempt to resolve any dispute through good faith negotiations for a period of at least 30 days. If the dispute cannot be resolved, users may use the European Commission\u2019s Online Dispute Resolution platform.</p>
              <p className="mb-3 font-medium">19.3 Exclusive jurisdiction</p>
              <p>Any legal action shall be brought exclusively in the competent courts of the jurisdiction where Else is established in Europe. You irrevocably consent to the exclusive jurisdiction of such courts.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">20. General provisions</h2>
              <p className="mb-3 font-medium">20.1 Entire agreement</p>
              <p className="mb-4">These Terms, together with our Privacy Policy, constitute the entire agreement between you and Else regarding the Service.</p>
              <p className="mb-3 font-medium">20.2 Severability</p>
              <p className="mb-4">If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect.</p>
              <p className="mb-3 font-medium">20.3 Waiver</p>
              <p className="mb-4">Our failure to enforce any right or provision of these Terms will not constitute a waiver of such right or provision.</p>
              <p className="mb-3 font-medium">20.4 Assignment</p>
              <p className="mb-4">You may not assign or transfer these Terms without our prior written consent. We may assign or transfer these Terms without restriction.</p>
              <p className="mb-3 font-medium">20.5 Force majeure</p>
              <p className="mb-4">We shall not be liable for any failure or delay in performance due to circumstances beyond our reasonable control.</p>
              <p className="mb-3 font-medium">20.6 Language</p>
              <p>These Terms are provided in English. If we provide a translation, the English version will control in the event of any conflict.</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">21. Contact information</h2>
              <p className="mb-3">For any questions, concerns, or notices regarding these Terms, please contact us at:</p>
              <p>Else</p>
              <p>Email: info@tryelse.xyz</p>
              <p>Website: https://tryelse.xyz</p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-semibold text-foreground">22. Acknowledgment</h2>
              <p>BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS AND CONDITIONS, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEM. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE SERVICE.</p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
